services:
  node-1:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT
    environment:
      - HZ_CLUSTERNAME=lab-2

  node-2:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT
    environment:
      - HZ_CLUSTERNAME=lab-2

  node-3:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT
    environment:
      - HZ_CLUSTERNAME=lab-2